version: '3'
services:
  app:
    container_name: backoffice
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
      - "8090:443"
    volumes:
      - ./www:/var/www/html/
